import os
from datetime import datetime
from flask import current_app
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from services.db_service import get_db


def save_report_record(user_id, report_name, file_path):
    db = get_db()
    db.execute(
        """
        INSERT INTO reports (user_id, report_name, file_path)
        VALUES (?, ?, ?)
        """,
        (user_id, report_name, file_path)
    )
    db.commit()


def get_user_reports(user_id):
    db = get_db()
    return db.execute(
        """
        SELECT * FROM reports
        WHERE user_id = ?
        ORDER BY created_at DESC
        """,
        (user_id,)
    ).fetchall()


def generate_business_report(user_id, summary, health_score, risk_level, recommendations):
    os.makedirs(current_app.config["REPORT_FOLDER"], exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_name = f"business_health_report_{timestamp}.pdf"
    file_path = os.path.join(current_app.config["REPORT_FOLDER"], report_name)

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    y = height - 60

    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, y, "CloudSentinel Insight AI")
    y -= 25

    c.setFont("Helvetica", 11)
    c.drawString(50, y, "AI-Powered Business Health Report for SMEs")
    y -= 35

    c.setFont("Helvetica", 10)
    c.drawString(50, y, f"Generated On: {datetime.now().strftime('%d %B %Y, %I:%M %p')}")
    y -= 35

    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, "1. Business Summary")
    y -= 22

    c.setFont("Helvetica", 10)
    lines = [
        f"Total Revenue: NGN {summary['total_income']:,.2f}",
        f"Total Expenses: NGN {summary['total_expenses']:,.2f}",
        f"Net Profit: NGN {summary['net_profit']:,.2f}",
        f"Profit Margin: {summary['profit_margin']:.2f}%",
        f"Transactions Analyzed: {summary['transactions']}",
    ]

    for line in lines:
        c.drawString(65, y, line)
        y -= 18

    y -= 18
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, "2. AI Analysis")
    y -= 22

    c.setFont("Helvetica", 10)
    c.drawString(65, y, f"Business Health Score: {health_score}%")
    y -= 18
    c.drawString(65, y, f"Risk Level: {risk_level}")
    y -= 35

    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, "3. AI Recommendations")
    y -= 22

    c.setFont("Helvetica", 10)

    if recommendations:
        for rec in recommendations:
            text = f"- {rec['priority']} Priority: {rec['title']} - {rec['message']}"
            wrapped = split_text(text, 95)

            for line in wrapped:
                c.drawString(65, y, line)
                y -= 15

                if y < 80:
                    c.showPage()
                    y = height - 60
                    c.setFont("Helvetica", 10)
            y -= 8
    else:
        c.drawString(65, y, "No recommendations available.")
        y -= 20

    y -= 15
    c.setFont("Helvetica-Bold", 13)
    c.drawString(50, y, "4. Professional Note")
    y -= 22

    c.setFont("Helvetica", 10)
    note = (
        "This report is generated from the transaction records uploaded by the user. "
        "It is designed to support business monitoring, early financial risk awareness, "
        "and data-driven decision-making. The insights provided are advisory and should "
        "be used together with professional accounting, business, or financial guidance "
        "where necessary. CloudSentinel Insight AI helps SMEs understand their numbers, "
        "identify risk areas, and improve operational planning."
    )

    for line in split_text(note, 95):
        c.drawString(65, y, line)
        y -= 15

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(50, 40, "Generated by CloudSentinel Insight AI | Cybersecurity • Compliance • Digital Solutions")

    c.save()

    save_report_record(user_id, report_name, file_path)

    return report_name


def split_text(text, max_chars):
    words = text.split()
    lines = []
    current = ""

    for word in words:
        if len(current + " " + word) <= max_chars:
            current += " " + word if current else word
        else:
            lines.append(current)
            current = word

    if current:
        lines.append(current)

    return lines